<?php

namespace WorkTrackerBundle\Repository;

/**
 * WorkTimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkTimeRepository extends \Doctrine\ORM\EntityRepository
{
}
