work_tracker_work_time:
    resource: "@WorkTrackerBundle/Controller/WorkTimeController.php"
    type:     annotation

work_tracker:
    resource: "@WorkTrackerBundle/Resources/config/routing.yml"
    prefix:   /

payment_get:
    path: /payment/{id}
    defaults: { _controller: PaymentBundle:Payment:get }
    requirements:
      id: '\d+'